# Pipeline Variables Configuration
# Variables parametrizadas para Azure DevOps Pipeline
# Formato: YAML con comentarios de cada sección

# ==============================================================================
# GLOBAL VARIABLES - Aplicables a todo el pipeline
# ==============================================================================
global_variables:
  # Debug y Logging
  system_debug: 'false'
  log_level: 'info'
  
  # Docker Configuration
  docker_buildkit: '1'
  buildkit_progress: 'plain'
  docker_context: '.'
  
  # Node.js Configuration
  node_version: '18.x'
  npm_registry: 'https://registry.npmjs.org/'
  npm_cache_clean_force: 'false'
  
  # Artifact Locations
  backend_path: 'backend'
  frontend_path: 'frontend'
  backend_dist: 'backend/dist'
  frontend_dist: 'frontend/dist'

# ==============================================================================
# ENVIRONMENT VARIABLES - Variables por entorno
# ==============================================================================
environments:
  # Development Environment
  development:
    node_env: 'development'
    log_level: 'debug'
    api_debug: 'true'
    vite_api_base_url: 'http://localhost:3000/api'
    vite_app_title: 'Task Manager - Development'
    database_host: 'dev-mongodb.eastus.cloudapp.azure.com'
    database_name: 'fullstack_test_dev'
    app_url: 'https://webapp-fullstack-test-dev.azurewebsites.net'
    
  # Staging Environment
  staging:
    node_env: 'staging'
    log_level: 'info'
    api_debug: 'false'
    vite_api_base_url: 'https://webapp-fullstack-test-staging.azurewebsites.net/api'
    vite_app_title: 'Task Manager - Staging'
    database_host: 'staging-mongodb.eastus.cloudapp.azure.com'
    database_name: 'fullstack_test_staging'
    app_url: 'https://webapp-fullstack-test-staging.azurewebsites.net'
    
  # Production Environment
  production:
    node_env: 'production'
    log_level: 'warn'
    api_debug: 'false'
    vite_api_base_url: 'https://webapp-fullstack-test.azurewebsites.net/api'
    vite_app_title: 'Task Manager'
    database_host: 'prod-mongodb.eastus.cloudapp.azure.com'
    database_name: 'fullstack_test_prod'
    app_url: 'https://webapp-fullstack-test.azurewebsites.net'

# ==============================================================================
# BUILD CONFIGURATION - Configuración de compilación
# ==============================================================================
build_configuration:
  # Backend Build
  backend:
    build_timeout_minutes: 30
    npm_ci_args: '--prefer-offline --no-audit'
    build_script: 'npm run build'
    lint_script: 'npm run lint'
    test_script: 'npm test'
    cache_key_prefix: 'backend-deps'
    artifacts_name: 'backend-build'
    artifacts_path: '$(Backend_Path)/dist'
    
  # Frontend Build
  frontend:
    build_timeout_minutes: 30
    npm_ci_args: '--prefer-offline --no-audit'
    build_script: 'npm run build'
    lint_script: 'npm run lint'
    test_script: 'npm test'
    cache_key_prefix: 'frontend-deps'
    artifacts_name: 'frontend-build'
    artifacts_path: '$(Frontend_Path)/dist'

# ==============================================================================
# DOCKER CONFIGURATION - Configuración de Docker
# ==============================================================================
docker_configuration:
  # Registry Configuration
  registry:
    name: 'acrfullstacktest'
    fqdn: '$(registry_name).azurecr.io'
    region: 'eastus'
    sku: 'Standard'
    
  # Backend Image Configuration
  backend_image:
    name: 'fullstack-test/backend'
    dockerfile: 'backend/Dockerfile'
    context: 'backend'
    build_args:
      - 'NODE_ENV=$(node_env_build)'
      - 'BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")'
      - 'VCS_REF=$(commit_sha)'
      - 'VERSION=$(build_number)'
    cache_from:
      - '$(registry_fqdn)/$(backend_image_name):latest'
    tags:
      - '$(build_number)'
      - 'latest'
      - '$(branch_name)'
      - '$(commit_sha_short)'
    
  # Frontend Image Configuration
  frontend_image:
    name: 'fullstack-test/frontend'
    dockerfile: 'frontend/Dockerfile'
    context: 'frontend'
    build_args:
      - 'NODE_ENV=$(node_env_build)'
      - 'BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")'
      - 'VCS_REF=$(commit_sha)'
      - 'VERSION=$(build_number)'
      - 'VITE_API_BASE_URL=$(vite_api_base_url)'
    cache_from:
      - '$(registry_fqdn)/$(frontend_image_name):latest'
    tags:
      - '$(build_number)'
      - 'latest'
      - '$(branch_name)'
      - '$(commit_sha_short)'

# ==============================================================================
# AZURE WEB APP CONFIGURATION - Configuración de Azure Web Apps
# ==============================================================================
azure_webapp_configuration:
  # General Configuration
  resource_group: 'rg-fullstack-test'
  location: 'East US'
  app_service_plan: 'asp-fullstack-test'
  container_registry_name: 'acrfullstacktest'
  
  # Development Web App
  development:
    name: 'webapp-fullstack-test-dev'
    backend_image: '$(registry_fqdn)/$(backend_image_name):$(build_number)'
    frontend_image: '$(registry_fqdn)/$(frontend_image_name):$(build_number)'
    app_service_plan: 'asp-fullstack-test-dev'
    sku: 'B1'
    instances: 1
    container_port: 3000
    
  # Staging Web App
  staging:
    name: 'webapp-fullstack-test-staging'
    backend_image: '$(registry_fqdn)/$(backend_image_name):$(build_number)'
    frontend_image: '$(registry_fqdn)/$(frontend_image_name):$(build_number)'
    app_service_plan: 'asp-fullstack-test-staging'
    sku: 'B2'
    instances: 2
    container_port: 3000
    
  # Production Web App
  production:
    name: 'webapp-fullstack-test'
    backend_image: '$(registry_fqdn)/$(backend_image_name):$(build_number)'
    frontend_image: '$(registry_fqdn)/$(frontend_image_name):$(build_number)'
    app_service_plan: 'asp-fullstack-test'
    sku: 'B3'
    instances: 3
    container_port: 3000

# ==============================================================================
# CONDITIONAL TRIGGERS - Condiciones para disparar stages
# ==============================================================================
triggers:
  # Build Triggers
  build_backend:
    always: true
    paths:
      - 'backend/**'
      - 'azure-pipelines.yml'
      - 'docker-compose.yml'
      
  build_frontend:
    always: true
    paths:
      - 'frontend/**'
      - 'azure-pipelines.yml'
      - 'docker-compose.yml'
  
  # Push to Registry - Solo en ramas principales
  push_to_acr:
    condition: |
      and(
        succeeded(),
        or(
          eq(variables['Build.SourceBranch'], 'refs/heads/master'),
          eq(variables['Build.SourceBranch'], 'refs/heads/develop'),
          startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')
        )
      )
  
  # Deploy Development - Solo desde develop
  deploy_development:
    condition: |
      and(
        succeeded(),
        eq(variables['Build.SourceBranch'], 'refs/heads/develop')
      )
  
  # Deploy Staging - Solo desde release/*
  deploy_staging:
    condition: |
      and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')
      )
  
  # Deploy Production - Solo desde master (con aprobación)
  deploy_production:
    condition: |
      and(
        succeeded(),
        eq(variables['Build.SourceBranch'], 'refs/heads/master')
      )
    requires_approval: true
    approvers:
      - 'project-admins'

# ==============================================================================
# SERVICE CONNECTIONS - Conexiones a servicios externos
# ==============================================================================
service_connections:
  # Azure Container Registry Connection
  azure_container_registry:
    name: 'AzureContainerRegistry'
    type: 'dockerRegistry'
    registryType: 'ACR'
    
  # Azure Subscription Connection
  azure_subscription:
    name: 'AzureSubscription'
    type: 'azureRM'
    
  # Service Principal for ACR
  acr_service_principal:
    type: 'azureRM'
    displayName: 'ACR Service Principal'

# ==============================================================================
# CACHE CONFIGURATION - Configuración de caché
# ==============================================================================
cache_configuration:
  # NPM Cache
  npm_cache:
    enabled: true
    restore_on_miss: true
    backend_cache_key: 'backend-deps-$(System.TeamProjectId)-$(Build.SourceVersion)'
    frontend_cache_key: 'frontend-deps-$(System.TeamProjectId)-$(Build.SourceVersion)'
    backend_path: '$(Backend_Path)/node_modules'
    frontend_path: '$(Frontend_Path)/node_modules'
    
  # Docker Layer Cache
  docker_cache:
    enabled: true
    cache_from_latest: true
    cache_to_docker: true

# ==============================================================================
# TIMEOUT CONFIGURATION - Configuración de timeouts
# ==============================================================================
timeouts:
  # Job Timeouts
  build_timeout_minutes: 30
  docker_build_timeout_seconds: 3600
  deployment_timeout_minutes: 20
  
  # Task Timeouts
  npm_timeout_minutes: 10
  docker_push_timeout_minutes: 15

# ==============================================================================
# NOTIFICATION CONFIGURATION - Configuración de notificaciones
# ==============================================================================
notifications:
  # Slack Configuration (opcional)
  slack:
    enabled: false
    webhook_url: '$(slack_webhook_url)'
    notify_on_failure: true
    notify_on_success: false
    
  # Email Configuration (opcional)
  email:
    enabled: false
    recipients:
      - 'devops@example.com'
    notify_on_failure: true
    notify_on_success: false

# ==============================================================================
# VERSIONING - Configuración de versionado
# ==============================================================================
versioning:
  # Build Number Format
  build_number_format: '$(Date:yyyyMMdd)$(Rev:.r)'
  
  # Image Tagging Strategy
  image_tags:
    - '$(build_number)'           # Build number: 20251226.1
    - 'latest'                     # Latest tag
    - '$(branch_name)'             # Branch name
    - '$(commit_sha_short)'        # Short commit SHA

# ==============================================================================
# SECURITY CONFIGURATION - Configuración de seguridad
# ==============================================================================
security:
  # Credential Management
  use_key_vault: true
  key_vault_name: 'kv-fullstack-test'
  key_vault_resource_group: '$(resource_group)'
  
  # Image Scanning
  scan_images: true
  fail_on_vulnerabilities: false
  vulnerability_threshold: 'high'
  
  # Access Control
  require_approval_for_production: true
  approval_timeout_minutes: 60

# ==============================================================================
# DEPLOYMENT CONFIGURATION - Configuración de despliegue
# ==============================================================================
deployment:
  # Strategy
  strategy: 'blue-green'  # O 'canary', 'rolling'
  
  # Health Check
  health_check:
    enabled: true
    endpoint: '/health'
    timeout_seconds: 30
    retries: 3
    
  # Rollback
  auto_rollback:
    enabled: true
    on_health_check_failure: true
    on_deployment_failure: true

---
# ==============================================================================
# EJEMPLOS DE USO EN YAML
# ==============================================================================

# En el archivo azure-pipelines.yml, usar estas variables así:

variables:
  # Build variables
  NODE_VERSION: '18.x'
  NODE_ENV_BUILD: 'production'
  BUILD_TIMEOUT_MINUTES: 30
  
  # Registry variables
  REGISTRY_NAME: 'acrfullstacktest'
  REGISTRY_FQDN: '$(REGISTRY_NAME).azurecr.io'
  BACKEND_IMAGE_NAME: 'fullstack-test/backend'
  FRONTEND_IMAGE_NAME: 'fullstack-test/frontend'
  
  # Azure Web App variables
  AZURE_RESOURCE_GROUP: 'rg-fullstack-test'
  AZURE_LOCATION: 'East US'

stages:
  - stage: Build_Backend
    variables:
      NODE_ENV: $(environments.development.node_env)
      VITE_API_BASE_URL: $(environments.development.vite_api_base_url)
    # ... rest of stage configuration
